// User
export const ERROR_RECEIVE_USER = 'ERROR_RECEIVE_USER';
export const REQUEST_USER = 'REQUEST_USER';
export const RECEIVE_USER = 'RECEIVE_USER';

export const ERROR_SIGN_IN = 'ERROR_SIGN_IN';
export const REQUEST_SIGN_IN = 'REQUEST_SIGN_IN';
export const SUCCESS_SIGN_IN = 'SUCCESS_SIGN_IN';

export const ERROR_SIGN_UP = 'ERROR_SIGN_UP';
export const REQUEST_SIGN_UP = 'REQUEST_SIGN_UP';
export const SUCCESS_SIGN_UP = 'SUCCESS_SIGN_UP';

export const REQUEST_SIGN_OUT = 'REQUEST_SIGN_OUT';

export const ADD_PLANETS_LOADING = "ADD_PLANETS_LOADING";
export const ADD_PLANETS_SUCCESS = "ADD_PLANETS_SUCCESS";
export const ADD_PLANETS_ERROR = "ADD_PLANETS_ERROR";

export const FETCH_PLANETS_LOADING = "FETCH_PLANETS_LOADING";
export const FETCH_PLANETS_SUCCESS = "FETCH_PLANETS_SUCCESS";
export const FETCH_PLANETS_ERROR = "FETCH_PLANETS_ERROR";

export const DELETE_PLANET_LOADING = "DELETE_PLANET_LOADING";
export const DELETE_PLANET_SUCCESS = "DELETE_PLANET_SUCCESS";
export const DELETE_PLANET_ERROR = "DELETE_PLANET_ERROR";

export const FETCH_PLANET_LOADING = "FETCH_PLANET_LOADING";
export const FETCH_PLANET_SUCCESS = "FETCH_PLANET_SUCCESS";
export const FETCH_PLANET_ERROR = "FETCH_PLANET_ERROR";


export const UPDATE_PLANET_LOADING = "UPDATE_PLANET_LOADING";
export const UPDATE_PLANET_SUCCESS = "UPDATE_PLANET_SUCCESS";
export const UPDATE_PLANET_ERROR = "UPDATE_PLANET_ERROR";

export const FILTER_PLANETS_LOADING = "FILTER_PLANETS_LOADING";
export const FILTER_PLANETS_SUCCESS = "FILTER_PLANETS_SUCCESS";
export const FILTER_PLANETS_ERROR = "FILTER_PLANETS_ERROR";

export const CLEAR_STATE = "CLEAR_STATE";